### ISSUE TITLE
Fails on startup

### ISSUE THREAD

**Issue by NickHeiner** [shawncplus/ranviermud#23]
I just git cloned and npm installed, then tried to run it. I get the following error:

```
$ node ranvier 
5 Oct 13:11:21 - START - Loading entities
5 Oct 13:11:21 - Loading command l10n... 
5 Oct 13:11:21 - Done
5 Oct 13:11:21 - Loading event l10n... 
5 Oct 13:11:21 - Done
5 Oct 13:11:21 - START - Starting server
5 Oct 13:11:21 - Setting autosave to 10 minutes.
5 Oct 13:11:21 - Setting respawn to 20 minutes.
5 Oct 13:11:21 - Examining plugin directory - /private/tmp/ranvier/ranviermud/src/../plugins/
5 Oct 13:11:21 - Loading rooms...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at init (/private/tmp/ranvier/ranviermud/ranvier:112:10)
    at Object.<anonymous> (/private/tmp/ranvier/ranviermud/ranvier:148:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Am I doing something wrong? Am I missing docs somewhere?

**Comment by marado** [comment]
#45 fixes this, the issue can bow be closed.
