### ISSUE TITLE
Error: Cannot find module 'apiai'

### ISSUE THREAD

**Issue by Loneblackfang** [shawncplus/ranviermud#322]
### Description
On server startup the server starts to boot up as normal but when it hits the LOAD: BEHAVIORS [npc] ranvier-sentient..  it throws an error Error: Cannot find module 'apiai'. this only happens on my windows server

### Expected outcome
to load in

### Actual outcome
module.js:545
    throw err;
    ^

Error: Cannot find module 'apiai'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\ (removed for privacy) \GitHub\ranviermud\bundles\ranvier-npc-behaviors\behaviors\npc\ranvier-sentient.js:24:15)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

### Steps to reproduce
this error shows up after a reclone of the repo

### Version of Ranvier

2.0.0

**Comment by Loneblackfang** [comment]
I did some digging and found the issue. It is that the Apiai folder is completely missing. had to pull the folder from an old dev server to fix it

**Comment by seanohue** [comment]
Hi @Loneblackfang ,

The root cause of this is that bundle's dependencies are now moved into a nested package.json file rather than the package in the root of the Ranvier repo.

Running the bundle-install command (`npm run bundle-install` if you're on Mac or Linux) will install the dependencies of each bundle.
